# name: Singularity Build (native)
# on: [push]
# jobs:
#   build:
#     name: Build
#     runs-on: ubuntu-20.04
#     steps:
    
#     - name: Set up Go 1.16.4
#       uses: actions/setup-go@v2
#       with:
#         go-version: 1.16.4
#       id: go
#     - name: Install Dependencies
#       run: |
#         sudo apt-get update && sudo apt-get install -y \
#           build-essential \
#           libssl-dev \
#           uuid-dev \
#           libgpgme11-dev \
#           squashfs-tools \
#           libseccomp-dev \
#           wget \
#           pkg-config \
#           git \
#           cryptsetup

#     - name: Install Singularity
#       env:
#         SINGULARITY_VERSION: 3.8.1
#         GOPATH: /tmp/go
#       run: |
#         mkdir -p $GOPATH
#         sudo mkdir -p /usr/local/var/singularity/mnt
#         mkdir -p $GOPATH/src/github.com/sylabs
#         cd $GOPATH/src/github.com/sylabs
#         wget -c https://github.com/sylabs/singularity/releases/download/v${SINGULARITY_VERSION}/singularity-ce-${SINGULARITY_VERSION}.tar.gz 
#         tar -xzf singularity-ce-${SINGULARITY_VERSION}.tar.gz 
#         cd singularity-ce-${SINGULARITY_VERSION}
#         ./mconfig -p /usr/local
#         make -C builddir
#         sudo make -C builddir install          

#     - name: Check Singularity version
#       run: |
#         singularity --version

#     - name: Check out code for the container build
#       uses: actions/checkout@v1

#     - name: Build Container
#       env:
#         SINGULARITY_RECIPE: dials_v1.recipe
#         OUTPUT_CONTAINER: dials_v1.sif
#       run: |
#        ls 
#        if [ -f "${SINGULARITY_RECIPE}" ]; then
#             sudo -E singularity build ${OUTPUT_CONTAINER} ${SINGULARITY_RECIPE}
#        else
#            echo "${SINGULARITY_RECIPE} is not found."
#            echo "Present working directory: $PWD"
#            ls
#        fi
